version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: incidentmanager
    ports:
      - "3307:3306"
    networks:
      - incident-network

  backend:
    image: incidentmanager-backend
    container_name: incident-manager-backend
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/incidentmanager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - incident-network

  frontend:
    image: incident-frontend
    container_name: incident-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - incident-network

networks:
  incident-network:
    driver: bridge
