version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: incidentmanager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./incidentmanager
    container_name: incident-manager-backend
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./incident-frontend
    container_name: incident-manager-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://host.docker.internal:8082
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
