version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M@nju790
      MYSQL_DATABASE: incidentmanager
      MYSQL_USER: root
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: incident-manager-backend
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: incident-manager-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://host.docker.internal:8082
